package game_db.entity;
// Generated 08-Sep-2012 14:13:48 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Cafegold generated by hbm2java
 */
public class Cafegold  implements java.io.Serializable {


     private Integer cafegoldid;
     private Dbzone dbzone;
     private String cafeip;
     private Date yaratimzamani;
     private Date expirezamani;
     private BigDecimal fiyat;
     private BigDecimal kalanborc;

    public Cafegold() {
    }

    public Cafegold(Dbzone dbzone, String cafeip, Date yaratimzamani, Date expirezamani, BigDecimal fiyat, BigDecimal kalanborc) {
       this.dbzone = dbzone;
       this.cafeip = cafeip;
       this.yaratimzamani = yaratimzamani;
       this.expirezamani = expirezamani;
       this.fiyat = fiyat;
       this.kalanborc = kalanborc;
    }
   
    public Integer getCafegoldid() {
        return this.cafegoldid;
    }
    
    public void setCafegoldid(Integer cafegoldid) {
        this.cafegoldid = cafegoldid;
    }
    public Dbzone getDbzone() {
        return this.dbzone;
    }
    
    public void setDbzone(Dbzone dbzone) {
        this.dbzone = dbzone;
    }
    public String getCafeip() {
        return this.cafeip;
    }
    
    public void setCafeip(String cafeip) {
        this.cafeip = cafeip;
    }
    public Date getYaratimzamani() {
        return this.yaratimzamani;
    }
    
    public void setYaratimzamani(Date yaratimzamani) {
        this.yaratimzamani = yaratimzamani;
    }
    public Date getExpirezamani() {
        return this.expirezamani;
    }
    
    public void setExpirezamani(Date expirezamani) {
        this.expirezamani = expirezamani;
    }
    public BigDecimal getFiyat() {
        return this.fiyat;
    }
    
    public void setFiyat(BigDecimal fiyat) {
        this.fiyat = fiyat;
    }
    public BigDecimal getKalanborc() {
        return this.kalanborc;
    }
    
    public void setKalanborc(BigDecimal kalanborc) {
        this.kalanborc = kalanborc;
    }




}


