package game_db.entity;
// Generated 08-Sep-2012 14:13:48 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dbroom generated by hbm2java
 */
public class Dbroom  implements java.io.Serializable {


     private Integer roomid;
     private Dbzone dbzone;
     private int roomnumber;
     private boolean isactive;
     private String roomname;
     private String roomgorunenname;
     private int roomnormalcapacity;
     private int roomgoldcapacity;
     private Date yaratimzamani;
     private Date expirezamani;
     private BigDecimal odafiyat;
     private BigDecimal odakalanborc;
     private int minimumgirispuan;
     private int minimumkonusmapuan;
     private String salontipi;
     private boolean isokey;
     private boolean isyuzbir;
     private String salontema;
     private String salongsparka;
     private String masareklam;
     private String masaorturengi;
     private String masabutonrengi;
     private Set roompublicmsglogs = new HashSet(0);
     private Set roomlevelpermsets = new HashSet(0);
     private Set gamelogs = new HashSet(0);
     private Set gorevhavuzus = new HashSet(0);
     private Set roomlevelipbans = new HashSet(0);
     private Set roomlevelbanlogs = new HashSet(0);

    public Dbroom() {
    }

	
    public Dbroom(Dbzone dbzone, int roomnumber, boolean isactive, String roomname, String roomgorunenname, int roomnormalcapacity, int roomgoldcapacity, Date yaratimzamani, Date expirezamani, BigDecimal odafiyat, BigDecimal odakalanborc, int minimumgirispuan, int minimumkonusmapuan, String salontipi, boolean isokey, boolean isyuzbir, String salontema, String salongsparka, String masareklam, String masaorturengi, String masabutonrengi) {
        this.dbzone = dbzone;
        this.roomnumber = roomnumber;
        this.isactive = isactive;
        this.roomname = roomname;
        this.roomgorunenname = roomgorunenname;
        this.roomnormalcapacity = roomnormalcapacity;
        this.roomgoldcapacity = roomgoldcapacity;
        this.yaratimzamani = yaratimzamani;
        this.expirezamani = expirezamani;
        this.odafiyat = odafiyat;
        this.odakalanborc = odakalanborc;
        this.minimumgirispuan = minimumgirispuan;
        this.minimumkonusmapuan = minimumkonusmapuan;
        this.salontipi = salontipi;
        this.isokey = isokey;
        this.isyuzbir = isyuzbir;
        this.salontema = salontema;
        this.salongsparka = salongsparka;
        this.masareklam = masareklam;
        this.masaorturengi = masaorturengi;
        this.masabutonrengi = masabutonrengi;
    }
    public Dbroom(Dbzone dbzone, int roomnumber, boolean isactive, String roomname, String roomgorunenname, int roomnormalcapacity, int roomgoldcapacity, Date yaratimzamani, Date expirezamani, BigDecimal odafiyat, BigDecimal odakalanborc, int minimumgirispuan, int minimumkonusmapuan, String salontipi, boolean isokey, boolean isyuzbir, String salontema, String salongsparka, String masareklam, String masaorturengi, String masabutonrengi, Set roompublicmsglogs, Set roomlevelpermsets, Set gamelogs, Set gorevhavuzus, Set roomlevelipbans, Set roomlevelbanlogs) {
       this.dbzone = dbzone;
       this.roomnumber = roomnumber;
       this.isactive = isactive;
       this.roomname = roomname;
       this.roomgorunenname = roomgorunenname;
       this.roomnormalcapacity = roomnormalcapacity;
       this.roomgoldcapacity = roomgoldcapacity;
       this.yaratimzamani = yaratimzamani;
       this.expirezamani = expirezamani;
       this.odafiyat = odafiyat;
       this.odakalanborc = odakalanborc;
       this.minimumgirispuan = minimumgirispuan;
       this.minimumkonusmapuan = minimumkonusmapuan;
       this.salontipi = salontipi;
       this.isokey = isokey;
       this.isyuzbir = isyuzbir;
       this.salontema = salontema;
       this.salongsparka = salongsparka;
       this.masareklam = masareklam;
       this.masaorturengi = masaorturengi;
       this.masabutonrengi = masabutonrengi;
       this.roompublicmsglogs = roompublicmsglogs;
       this.roomlevelpermsets = roomlevelpermsets;
       this.gamelogs = gamelogs;
       this.gorevhavuzus = gorevhavuzus;
       this.roomlevelipbans = roomlevelipbans;
       this.roomlevelbanlogs = roomlevelbanlogs;
    }
   
    public Integer getRoomid() {
        return this.roomid;
    }
    
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }
    public Dbzone getDbzone() {
        return this.dbzone;
    }
    
    public void setDbzone(Dbzone dbzone) {
        this.dbzone = dbzone;
    }
    public int getRoomnumber() {
        return this.roomnumber;
    }
    
    public void setRoomnumber(int roomnumber) {
        this.roomnumber = roomnumber;
    }
    public boolean isIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(boolean isactive) {
        this.isactive = isactive;
    }
    public String getRoomname() {
        return this.roomname;
    }
    
    public void setRoomname(String roomname) {
        this.roomname = roomname;
    }
    public String getRoomgorunenname() {
        return this.roomgorunenname;
    }
    
    public void setRoomgorunenname(String roomgorunenname) {
        this.roomgorunenname = roomgorunenname;
    }
    public int getRoomnormalcapacity() {
        return this.roomnormalcapacity;
    }
    
    public void setRoomnormalcapacity(int roomnormalcapacity) {
        this.roomnormalcapacity = roomnormalcapacity;
    }
    public int getRoomgoldcapacity() {
        return this.roomgoldcapacity;
    }
    
    public void setRoomgoldcapacity(int roomgoldcapacity) {
        this.roomgoldcapacity = roomgoldcapacity;
    }
    public Date getYaratimzamani() {
        return this.yaratimzamani;
    }
    
    public void setYaratimzamani(Date yaratimzamani) {
        this.yaratimzamani = yaratimzamani;
    }
    public Date getExpirezamani() {
        return this.expirezamani;
    }
    
    public void setExpirezamani(Date expirezamani) {
        this.expirezamani = expirezamani;
    }
    public BigDecimal getOdafiyat() {
        return this.odafiyat;
    }
    
    public void setOdafiyat(BigDecimal odafiyat) {
        this.odafiyat = odafiyat;
    }
    public BigDecimal getOdakalanborc() {
        return this.odakalanborc;
    }
    
    public void setOdakalanborc(BigDecimal odakalanborc) {
        this.odakalanborc = odakalanborc;
    }
    public int getMinimumgirispuan() {
        return this.minimumgirispuan;
    }
    
    public void setMinimumgirispuan(int minimumgirispuan) {
        this.minimumgirispuan = minimumgirispuan;
    }
    public int getMinimumkonusmapuan() {
        return this.minimumkonusmapuan;
    }
    
    public void setMinimumkonusmapuan(int minimumkonusmapuan) {
        this.minimumkonusmapuan = minimumkonusmapuan;
    }
    public String getSalontipi() {
        return this.salontipi;
    }
    
    public void setSalontipi(String salontipi) {
        this.salontipi = salontipi;
    }
    public boolean isIsokey() {
        return this.isokey;
    }
    
    public void setIsokey(boolean isokey) {
        this.isokey = isokey;
    }
    public boolean isIsyuzbir() {
        return this.isyuzbir;
    }
    
    public void setIsyuzbir(boolean isyuzbir) {
        this.isyuzbir = isyuzbir;
    }
    public String getSalontema() {
        return this.salontema;
    }
    
    public void setSalontema(String salontema) {
        this.salontema = salontema;
    }
    public String getSalongsparka() {
        return this.salongsparka;
    }
    
    public void setSalongsparka(String salongsparka) {
        this.salongsparka = salongsparka;
    }
    public String getMasareklam() {
        return this.masareklam;
    }
    
    public void setMasareklam(String masareklam) {
        this.masareklam = masareklam;
    }
    public String getMasaorturengi() {
        return this.masaorturengi;
    }
    
    public void setMasaorturengi(String masaorturengi) {
        this.masaorturengi = masaorturengi;
    }
    public String getMasabutonrengi() {
        return this.masabutonrengi;
    }
    
    public void setMasabutonrengi(String masabutonrengi) {
        this.masabutonrengi = masabutonrengi;
    }
    public Set getRoompublicmsglogs() {
        return this.roompublicmsglogs;
    }
    
    public void setRoompublicmsglogs(Set roompublicmsglogs) {
        this.roompublicmsglogs = roompublicmsglogs;
    }
    public Set getRoomlevelpermsets() {
        return this.roomlevelpermsets;
    }
    
    public void setRoomlevelpermsets(Set roomlevelpermsets) {
        this.roomlevelpermsets = roomlevelpermsets;
    }
    public Set getGamelogs() {
        return this.gamelogs;
    }
    
    public void setGamelogs(Set gamelogs) {
        this.gamelogs = gamelogs;
    }
    public Set getGorevhavuzus() {
        return this.gorevhavuzus;
    }
    
    public void setGorevhavuzus(Set gorevhavuzus) {
        this.gorevhavuzus = gorevhavuzus;
    }
    public Set getRoomlevelipbans() {
        return this.roomlevelipbans;
    }
    
    public void setRoomlevelipbans(Set roomlevelipbans) {
        this.roomlevelipbans = roomlevelipbans;
    }
    public Set getRoomlevelbanlogs() {
        return this.roomlevelbanlogs;
    }
    
    public void setRoomlevelbanlogs(Set roomlevelbanlogs) {
        this.roomlevelbanlogs = roomlevelbanlogs;
    }




}


