package game_db.entity;
// Generated 08-Sep-2012 14:13:48 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Gamelog generated by hbm2java
 */
public class Gamelog  implements java.io.Serializable {


     private Integer gameid;
     private Dbroom dbroom;
     private int biruserid;
     private int ikiuserid;
     private Integer ucuserid;
     private Integer dortuserid;
     private Integer besuserid;
     private Integer altiuserid;
     private Integer yediuserid;
     private Integer sekizuserid;
     private Integer dokuzuserid;
     private int birdiffscore;
     private int ikidiffscore;
     private Integer ucdiffscore;
     private Integer dortdiffscore;
     private Integer besdiffscore;
     private Integer altidiffscore;
     private Integer yedidiffscore;
     private Integer sekizdiffscore;
     private Integer dokuzdiffscore;
     private String gametip;
     private Set gamepublicmsglogs = new HashSet(0);

    public Gamelog() {
    }

	
    public Gamelog(Dbroom dbroom, int biruserid, int ikiuserid, int birdiffscore, int ikidiffscore, String gametip) {
        this.dbroom = dbroom;
        this.biruserid = biruserid;
        this.ikiuserid = ikiuserid;
        this.birdiffscore = birdiffscore;
        this.ikidiffscore = ikidiffscore;
        this.gametip = gametip;
    }
    public Gamelog(Dbroom dbroom, int biruserid, int ikiuserid, Integer ucuserid, Integer dortuserid, Integer besuserid, Integer altiuserid, Integer yediuserid, Integer sekizuserid, Integer dokuzuserid, int birdiffscore, int ikidiffscore, Integer ucdiffscore, Integer dortdiffscore, Integer besdiffscore, Integer altidiffscore, Integer yedidiffscore, Integer sekizdiffscore, Integer dokuzdiffscore, String gametip, Set gamepublicmsglogs) {
       this.dbroom = dbroom;
       this.biruserid = biruserid;
       this.ikiuserid = ikiuserid;
       this.ucuserid = ucuserid;
       this.dortuserid = dortuserid;
       this.besuserid = besuserid;
       this.altiuserid = altiuserid;
       this.yediuserid = yediuserid;
       this.sekizuserid = sekizuserid;
       this.dokuzuserid = dokuzuserid;
       this.birdiffscore = birdiffscore;
       this.ikidiffscore = ikidiffscore;
       this.ucdiffscore = ucdiffscore;
       this.dortdiffscore = dortdiffscore;
       this.besdiffscore = besdiffscore;
       this.altidiffscore = altidiffscore;
       this.yedidiffscore = yedidiffscore;
       this.sekizdiffscore = sekizdiffscore;
       this.dokuzdiffscore = dokuzdiffscore;
       this.gametip = gametip;
       this.gamepublicmsglogs = gamepublicmsglogs;
    }
   
    public Integer getGameid() {
        return this.gameid;
    }
    
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }
    public Dbroom getDbroom() {
        return this.dbroom;
    }
    
    public void setDbroom(Dbroom dbroom) {
        this.dbroom = dbroom;
    }
    public int getBiruserid() {
        return this.biruserid;
    }
    
    public void setBiruserid(int biruserid) {
        this.biruserid = biruserid;
    }
    public int getIkiuserid() {
        return this.ikiuserid;
    }
    
    public void setIkiuserid(int ikiuserid) {
        this.ikiuserid = ikiuserid;
    }
    public Integer getUcuserid() {
        return this.ucuserid;
    }
    
    public void setUcuserid(Integer ucuserid) {
        this.ucuserid = ucuserid;
    }
    public Integer getDortuserid() {
        return this.dortuserid;
    }
    
    public void setDortuserid(Integer dortuserid) {
        this.dortuserid = dortuserid;
    }
    public Integer getBesuserid() {
        return this.besuserid;
    }
    
    public void setBesuserid(Integer besuserid) {
        this.besuserid = besuserid;
    }
    public Integer getAltiuserid() {
        return this.altiuserid;
    }
    
    public void setAltiuserid(Integer altiuserid) {
        this.altiuserid = altiuserid;
    }
    public Integer getYediuserid() {
        return this.yediuserid;
    }
    
    public void setYediuserid(Integer yediuserid) {
        this.yediuserid = yediuserid;
    }
    public Integer getSekizuserid() {
        return this.sekizuserid;
    }
    
    public void setSekizuserid(Integer sekizuserid) {
        this.sekizuserid = sekizuserid;
    }
    public Integer getDokuzuserid() {
        return this.dokuzuserid;
    }
    
    public void setDokuzuserid(Integer dokuzuserid) {
        this.dokuzuserid = dokuzuserid;
    }
    public int getBirdiffscore() {
        return this.birdiffscore;
    }
    
    public void setBirdiffscore(int birdiffscore) {
        this.birdiffscore = birdiffscore;
    }
    public int getIkidiffscore() {
        return this.ikidiffscore;
    }
    
    public void setIkidiffscore(int ikidiffscore) {
        this.ikidiffscore = ikidiffscore;
    }
    public Integer getUcdiffscore() {
        return this.ucdiffscore;
    }
    
    public void setUcdiffscore(Integer ucdiffscore) {
        this.ucdiffscore = ucdiffscore;
    }
    public Integer getDortdiffscore() {
        return this.dortdiffscore;
    }
    
    public void setDortdiffscore(Integer dortdiffscore) {
        this.dortdiffscore = dortdiffscore;
    }
    public Integer getBesdiffscore() {
        return this.besdiffscore;
    }
    
    public void setBesdiffscore(Integer besdiffscore) {
        this.besdiffscore = besdiffscore;
    }
    public Integer getAltidiffscore() {
        return this.altidiffscore;
    }
    
    public void setAltidiffscore(Integer altidiffscore) {
        this.altidiffscore = altidiffscore;
    }
    public Integer getYedidiffscore() {
        return this.yedidiffscore;
    }
    
    public void setYedidiffscore(Integer yedidiffscore) {
        this.yedidiffscore = yedidiffscore;
    }
    public Integer getSekizdiffscore() {
        return this.sekizdiffscore;
    }
    
    public void setSekizdiffscore(Integer sekizdiffscore) {
        this.sekizdiffscore = sekizdiffscore;
    }
    public Integer getDokuzdiffscore() {
        return this.dokuzdiffscore;
    }
    
    public void setDokuzdiffscore(Integer dokuzdiffscore) {
        this.dokuzdiffscore = dokuzdiffscore;
    }
    public String getGametip() {
        return this.gametip;
    }
    
    public void setGametip(String gametip) {
        this.gametip = gametip;
    }
    public Set getGamepublicmsglogs() {
        return this.gamepublicmsglogs;
    }
    
    public void setGamepublicmsglogs(Set gamepublicmsglogs) {
        this.gamepublicmsglogs = gamepublicmsglogs;
    }




}


