package game_db.entity;
// Generated 08-Sep-2012 14:13:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Gamepublicmsglog generated by hbm2java
 */
public class Gamepublicmsglog  implements java.io.Serializable {


     private Integer gamepublicmsgid;
     private Gamelog gamelog;
     private int sourceuserid;
     private Date msgtime;
     private String msg;

    public Gamepublicmsglog() {
    }

    public Gamepublicmsglog(Gamelog gamelog, int sourceuserid, Date msgtime, String msg) {
       this.gamelog = gamelog;
       this.sourceuserid = sourceuserid;
       this.msgtime = msgtime;
       this.msg = msg;
    }
   
    public Integer getGamepublicmsgid() {
        return this.gamepublicmsgid;
    }
    
    public void setGamepublicmsgid(Integer gamepublicmsgid) {
        this.gamepublicmsgid = gamepublicmsgid;
    }
    public Gamelog getGamelog() {
        return this.gamelog;
    }
    
    public void setGamelog(Gamelog gamelog) {
        this.gamelog = gamelog;
    }
    public int getSourceuserid() {
        return this.sourceuserid;
    }
    
    public void setSourceuserid(int sourceuserid) {
        this.sourceuserid = sourceuserid;
    }
    public Date getMsgtime() {
        return this.msgtime;
    }
    
    public void setMsgtime(Date msgtime) {
        this.msgtime = msgtime;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }




}


