package game_db.entity;
// Generated 08-Sep-2012 14:13:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Gorevhavuzu generated by hbm2java
 */
public class Gorevhavuzu  implements java.io.Serializable {


     private Integer gorevid;
     private Userlogin userlogin;
     private Dbroom dbroom;
     private Dbzone dbzone;
     private String gorevtip;
     private String gorevaciklama;
     private int gerekenminlevel;
     private Date talepzaman;
     private String gorevdurumu;
     private Date gorevkabulzamani;
     private Integer gorevialanuserid;
     private String gorevdurumaciklama;
     private Date gorevsonuczamani;

    public Gorevhavuzu() {
    }

	
    public Gorevhavuzu(Userlogin userlogin, Dbzone dbzone, String gorevtip, String gorevaciklama, int gerekenminlevel, Date talepzaman, String gorevdurumu) {
        this.userlogin = userlogin;
        this.dbzone = dbzone;
        this.gorevtip = gorevtip;
        this.gorevaciklama = gorevaciklama;
        this.gerekenminlevel = gerekenminlevel;
        this.talepzaman = talepzaman;
        this.gorevdurumu = gorevdurumu;
    }
    public Gorevhavuzu(Userlogin userlogin, Dbroom dbroom, Dbzone dbzone, String gorevtip, String gorevaciklama, int gerekenminlevel, Date talepzaman, String gorevdurumu, Date gorevkabulzamani, Integer gorevialanuserid, String gorevdurumaciklama, Date gorevsonuczamani) {
       this.userlogin = userlogin;
       this.dbroom = dbroom;
       this.dbzone = dbzone;
       this.gorevtip = gorevtip;
       this.gorevaciklama = gorevaciklama;
       this.gerekenminlevel = gerekenminlevel;
       this.talepzaman = talepzaman;
       this.gorevdurumu = gorevdurumu;
       this.gorevkabulzamani = gorevkabulzamani;
       this.gorevialanuserid = gorevialanuserid;
       this.gorevdurumaciklama = gorevdurumaciklama;
       this.gorevsonuczamani = gorevsonuczamani;
    }
   
    public Integer getGorevid() {
        return this.gorevid;
    }
    
    public void setGorevid(Integer gorevid) {
        this.gorevid = gorevid;
    }
    public Userlogin getUserlogin() {
        return this.userlogin;
    }
    
    public void setUserlogin(Userlogin userlogin) {
        this.userlogin = userlogin;
    }
    public Dbroom getDbroom() {
        return this.dbroom;
    }
    
    public void setDbroom(Dbroom dbroom) {
        this.dbroom = dbroom;
    }
    public Dbzone getDbzone() {
        return this.dbzone;
    }
    
    public void setDbzone(Dbzone dbzone) {
        this.dbzone = dbzone;
    }
    public String getGorevtip() {
        return this.gorevtip;
    }
    
    public void setGorevtip(String gorevtip) {
        this.gorevtip = gorevtip;
    }
    public String getGorevaciklama() {
        return this.gorevaciklama;
    }
    
    public void setGorevaciklama(String gorevaciklama) {
        this.gorevaciklama = gorevaciklama;
    }
    public int getGerekenminlevel() {
        return this.gerekenminlevel;
    }
    
    public void setGerekenminlevel(int gerekenminlevel) {
        this.gerekenminlevel = gerekenminlevel;
    }
    public Date getTalepzaman() {
        return this.talepzaman;
    }
    
    public void setTalepzaman(Date talepzaman) {
        this.talepzaman = talepzaman;
    }
    public String getGorevdurumu() {
        return this.gorevdurumu;
    }
    
    public void setGorevdurumu(String gorevdurumu) {
        this.gorevdurumu = gorevdurumu;
    }
    public Date getGorevkabulzamani() {
        return this.gorevkabulzamani;
    }
    
    public void setGorevkabulzamani(Date gorevkabulzamani) {
        this.gorevkabulzamani = gorevkabulzamani;
    }
    public Integer getGorevialanuserid() {
        return this.gorevialanuserid;
    }
    
    public void setGorevialanuserid(Integer gorevialanuserid) {
        this.gorevialanuserid = gorevialanuserid;
    }
    public String getGorevdurumaciklama() {
        return this.gorevdurumaciklama;
    }
    
    public void setGorevdurumaciklama(String gorevdurumaciklama) {
        this.gorevdurumaciklama = gorevdurumaciklama;
    }
    public Date getGorevsonuczamani() {
        return this.gorevsonuczamani;
    }
    
    public void setGorevsonuczamani(Date gorevsonuczamani) {
        this.gorevsonuczamani = gorevsonuczamani;
    }




}


