package game_db.entity;
// Generated 08-Sep-2012 14:13:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Roomlevelbanlog generated by hbm2java
 */
public class Roomlevelbanlog  implements java.io.Serializable {


     private Integer roombanid;
     private Dbroom dbroom;
     private Userlogin userlogin;
     private Date banstart;
     private Date banend;
     private String bansebep;
     private int bankoyanuserid;
     private Integer bankaldiranuserid;
     private String bannot;

    public Roomlevelbanlog() {
    }

	
    public Roomlevelbanlog(Dbroom dbroom, Userlogin userlogin, Date banstart, Date banend, String bansebep, int bankoyanuserid) {
        this.dbroom = dbroom;
        this.userlogin = userlogin;
        this.banstart = banstart;
        this.banend = banend;
        this.bansebep = bansebep;
        this.bankoyanuserid = bankoyanuserid;
    }
    public Roomlevelbanlog(Dbroom dbroom, Userlogin userlogin, Date banstart, Date banend, String bansebep, int bankoyanuserid, Integer bankaldiranuserid, String bannot) {
       this.dbroom = dbroom;
       this.userlogin = userlogin;
       this.banstart = banstart;
       this.banend = banend;
       this.bansebep = bansebep;
       this.bankoyanuserid = bankoyanuserid;
       this.bankaldiranuserid = bankaldiranuserid;
       this.bannot = bannot;
    }
   
    public Integer getRoombanid() {
        return this.roombanid;
    }
    
    public void setRoombanid(Integer roombanid) {
        this.roombanid = roombanid;
    }
    public Dbroom getDbroom() {
        return this.dbroom;
    }
    
    public void setDbroom(Dbroom dbroom) {
        this.dbroom = dbroom;
    }
    public Userlogin getUserlogin() {
        return this.userlogin;
    }
    
    public void setUserlogin(Userlogin userlogin) {
        this.userlogin = userlogin;
    }
    public Date getBanstart() {
        return this.banstart;
    }
    
    public void setBanstart(Date banstart) {
        this.banstart = banstart;
    }
    public Date getBanend() {
        return this.banend;
    }
    
    public void setBanend(Date banend) {
        this.banend = banend;
    }
    public String getBansebep() {
        return this.bansebep;
    }
    
    public void setBansebep(String bansebep) {
        this.bansebep = bansebep;
    }
    public int getBankoyanuserid() {
        return this.bankoyanuserid;
    }
    
    public void setBankoyanuserid(int bankoyanuserid) {
        this.bankoyanuserid = bankoyanuserid;
    }
    public Integer getBankaldiranuserid() {
        return this.bankaldiranuserid;
    }
    
    public void setBankaldiranuserid(Integer bankaldiranuserid) {
        this.bankaldiranuserid = bankaldiranuserid;
    }
    public String getBannot() {
        return this.bannot;
    }
    
    public void setBannot(String bannot) {
        this.bannot = bannot;
    }




}


