package game_db.entity;
// Generated 08-Sep-2012 14:13:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Serverlvlnickban generated by hbm2java
 */
public class Serverlvlnickban  implements java.io.Serializable {


     private Integer serverbanid;
     private Userlogin userlogin;
     private Dbzone dbzone;
     private Date banstart;
     private Date banend;
     private int bankoyanuserid;
     private String bansebep;
     private Integer bankaldiranuserid;
     private String bannot;

    public Serverlvlnickban() {
    }

	
    public Serverlvlnickban(Userlogin userlogin, Dbzone dbzone, Date banstart, Date banend, int bankoyanuserid, String bansebep) {
        this.userlogin = userlogin;
        this.dbzone = dbzone;
        this.banstart = banstart;
        this.banend = banend;
        this.bankoyanuserid = bankoyanuserid;
        this.bansebep = bansebep;
    }
    public Serverlvlnickban(Userlogin userlogin, Dbzone dbzone, Date banstart, Date banend, int bankoyanuserid, String bansebep, Integer bankaldiranuserid, String bannot) {
       this.userlogin = userlogin;
       this.dbzone = dbzone;
       this.banstart = banstart;
       this.banend = banend;
       this.bankoyanuserid = bankoyanuserid;
       this.bansebep = bansebep;
       this.bankaldiranuserid = bankaldiranuserid;
       this.bannot = bannot;
    }
   
    public Integer getServerbanid() {
        return this.serverbanid;
    }
    
    public void setServerbanid(Integer serverbanid) {
        this.serverbanid = serverbanid;
    }
    public Userlogin getUserlogin() {
        return this.userlogin;
    }
    
    public void setUserlogin(Userlogin userlogin) {
        this.userlogin = userlogin;
    }
    public Dbzone getDbzone() {
        return this.dbzone;
    }
    
    public void setDbzone(Dbzone dbzone) {
        this.dbzone = dbzone;
    }
    public Date getBanstart() {
        return this.banstart;
    }
    
    public void setBanstart(Date banstart) {
        this.banstart = banstart;
    }
    public Date getBanend() {
        return this.banend;
    }
    
    public void setBanend(Date banend) {
        this.banend = banend;
    }
    public int getBankoyanuserid() {
        return this.bankoyanuserid;
    }
    
    public void setBankoyanuserid(int bankoyanuserid) {
        this.bankoyanuserid = bankoyanuserid;
    }
    public String getBansebep() {
        return this.bansebep;
    }
    
    public void setBansebep(String bansebep) {
        this.bansebep = bansebep;
    }
    public Integer getBankaldiranuserid() {
        return this.bankaldiranuserid;
    }
    
    public void setBankaldiranuserid(Integer bankaldiranuserid) {
        this.bankaldiranuserid = bankaldiranuserid;
    }
    public String getBannot() {
        return this.bannot;
    }
    
    public void setBannot(String bannot) {
        this.bannot = bannot;
    }




}


