package game_db.entity;
// Generated 08-Sep-2012 14:13:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Userprivatemsglog generated by hbm2java
 */
public class Userprivatemsglog  implements java.io.Serializable {


     private Integer logid;
     private Userlogin userlogin;
     private Dbzone dbzone;
     private String tonickname;
     private String msg;
     private Date msgdate;

    public Userprivatemsglog() {
    }

    public Userprivatemsglog(Userlogin userlogin, Dbzone dbzone, String tonickname, String msg, Date msgdate) {
       this.userlogin = userlogin;
       this.dbzone = dbzone;
       this.tonickname = tonickname;
       this.msg = msg;
       this.msgdate = msgdate;
    }
   
    public Integer getLogid() {
        return this.logid;
    }
    
    public void setLogid(Integer logid) {
        this.logid = logid;
    }
    public Userlogin getUserlogin() {
        return this.userlogin;
    }
    
    public void setUserlogin(Userlogin userlogin) {
        this.userlogin = userlogin;
    }
    public Dbzone getDbzone() {
        return this.dbzone;
    }
    
    public void setDbzone(Dbzone dbzone) {
        this.dbzone = dbzone;
    }
    public String getTonickname() {
        return this.tonickname;
    }
    
    public void setTonickname(String tonickname) {
        this.tonickname = tonickname;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }
    public Date getMsgdate() {
        return this.msgdate;
    }
    
    public void setMsgdate(Date msgdate) {
        this.msgdate = msgdate;
    }




}


