package game_db.entity;
// Generated 08-Sep-2012 14:13:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Usercnnlog generated by hbm2java
 */
public class Usercnnlog  implements java.io.Serializable {


     private Integer cnnid;
     private Userlogin userlogin;
     private Dbzone dbzone;
     private Date logintime;
     private Date logouttime;
     private String cnnip;

    public Usercnnlog() {
    }

	
    public Usercnnlog(Userlogin userlogin, Dbzone dbzone, Date logintime, String cnnip) {
        this.userlogin = userlogin;
        this.dbzone = dbzone;
        this.logintime = logintime;
        this.cnnip = cnnip;
    }
    public Usercnnlog(Userlogin userlogin, Dbzone dbzone, Date logintime, Date logouttime, String cnnip) {
       this.userlogin = userlogin;
       this.dbzone = dbzone;
       this.logintime = logintime;
       this.logouttime = logouttime;
       this.cnnip = cnnip;
    }
   
    public Integer getCnnid() {
        return this.cnnid;
    }
    
    public void setCnnid(Integer cnnid) {
        this.cnnid = cnnid;
    }
    public Userlogin getUserlogin() {
        return this.userlogin;
    }
    
    public void setUserlogin(Userlogin userlogin) {
        this.userlogin = userlogin;
    }
    public Dbzone getDbzone() {
        return this.dbzone;
    }
    
    public void setDbzone(Dbzone dbzone) {
        this.dbzone = dbzone;
    }
    public Date getLogintime() {
        return this.logintime;
    }
    
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }
    public Date getLogouttime() {
        return this.logouttime;
    }
    
    public void setLogouttime(Date logouttime) {
        this.logouttime = logouttime;
    }
    public String getCnnip() {
        return this.cnnip;
    }
    
    public void setCnnip(String cnnip) {
        this.cnnip = cnnip;
    }




}


