package game_db.entity;
// Generated 08-Sep-2012 14:13:48 by Hibernate Tools 3.2.1.GA



/**
 * Userbuddydata generated by hbm2java
 */
public class Userbuddydata  implements java.io.Serializable {


     private Integer userbuddataid;
     private Userlogin userlogin;
     private String buddyesname;
     private String buddynickname;

    public Userbuddydata() {
    }

    public Userbuddydata(Userlogin userlogin, String buddyesname, String buddynickname) {
       this.userlogin = userlogin;
       this.buddyesname = buddyesname;
       this.buddynickname = buddynickname;
    }
   
    public Integer getUserbuddataid() {
        return this.userbuddataid;
    }
    
    public void setUserbuddataid(Integer userbuddataid) {
        this.userbuddataid = userbuddataid;
    }
    public Userlogin getUserlogin() {
        return this.userlogin;
    }
    
    public void setUserlogin(Userlogin userlogin) {
        this.userlogin = userlogin;
    }
    public String getBuddyesname() {
        return this.buddyesname;
    }
    
    public void setBuddyesname(String buddyesname) {
        this.buddyesname = buddyesname;
    }
    public String getBuddynickname() {
        return this.buddynickname;
    }
    
    public void setBuddynickname(String buddynickname) {
        this.buddynickname = buddynickname;
    }




}


