package game_db.entity;
// Generated 08-Sep-2012 14:13:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Userlogin generated by hbm2java
 */
public class Userlogin  implements java.io.Serializable {


     private Integer userid;
     private Dbzone dbzone;
     private String name;
     private String nickname;
     private String password;
     private String email;
     private String gender;
     private Date userbirthday;
     private boolean isaccountactive;
     private boolean siteyononaydurum;
     private String activationcode;
     private String usercity;
     private boolean isgold;
     private int serverpermlevel;
     private String avatarpath;
     private boolean ishidden;
     private Integer atayanuserid;
     private Date goldexpirydate;
     private Set roomlevelpermsets = new HashSet(0);
     private Set serverlvlipbans = new HashSet(0);
     private Set userprivatemsglogs = new HashSet(0);
     private Set serverlvlnickbans = new HashSet(0);
     private Set scores = new HashSet(0);
     private Set usercnnlogs = new HashSet(0);
     private Set roomlevelbanlogs = new HashSet(0);
     private Set userbuddydatas = new HashSet(0);
     private Set gorevhavuzus = new HashSet(0);

    public Userlogin() {
    }

	
    public Userlogin(Dbzone dbzone, String name, String nickname, String password, String email, String gender, Date userbirthday, boolean isaccountactive, boolean siteyononaydurum, String activationcode, boolean isgold, int serverpermlevel, String avatarpath, boolean ishidden) {
        this.dbzone = dbzone;
        this.name = name;
        this.nickname = nickname;
        this.password = password;
        this.email = email;
        this.gender = gender;
        this.userbirthday = userbirthday;
        this.isaccountactive = isaccountactive;
        this.siteyononaydurum = siteyononaydurum;
        this.activationcode = activationcode;
        this.isgold = isgold;
        this.serverpermlevel = serverpermlevel;
        this.avatarpath = avatarpath;
        this.ishidden = ishidden;
    }
    public Userlogin(Dbzone dbzone, String name, String nickname, String password, String email, String gender, Date userbirthday, boolean isaccountactive, boolean siteyononaydurum, String activationcode, String usercity, boolean isgold, int serverpermlevel, String avatarpath, boolean ishidden, Integer atayanuserid, Date goldexpirydate, Set roomlevelpermsets, Set serverlvlipbans, Set userprivatemsglogs, Set serverlvlnickbans, Set scores, Set usercnnlogs, Set roomlevelbanlogs, Set userbuddydatas, Set gorevhavuzus) {
       this.dbzone = dbzone;
       this.name = name;
       this.nickname = nickname;
       this.password = password;
       this.email = email;
       this.gender = gender;
       this.userbirthday = userbirthday;
       this.isaccountactive = isaccountactive;
       this.siteyononaydurum = siteyononaydurum;
       this.activationcode = activationcode;
       this.usercity = usercity;
       this.isgold = isgold;
       this.serverpermlevel = serverpermlevel;
       this.avatarpath = avatarpath;
       this.ishidden = ishidden;
       this.atayanuserid = atayanuserid;
       this.goldexpirydate = goldexpirydate;
       this.roomlevelpermsets = roomlevelpermsets;
       this.serverlvlipbans = serverlvlipbans;
       this.userprivatemsglogs = userprivatemsglogs;
       this.serverlvlnickbans = serverlvlnickbans;
       this.scores = scores;
       this.usercnnlogs = usercnnlogs;
       this.roomlevelbanlogs = roomlevelbanlogs;
       this.userbuddydatas = userbuddydatas;
       this.gorevhavuzus = gorevhavuzus;
    }
   
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    public Dbzone getDbzone() {
        return this.dbzone;
    }
    
    public void setDbzone(Dbzone dbzone) {
        this.dbzone = dbzone;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getUserbirthday() {
        return this.userbirthday;
    }
    
    public void setUserbirthday(Date userbirthday) {
        this.userbirthday = userbirthday;
    }
    public boolean isIsaccountactive() {
        return this.isaccountactive;
    }
    
    public void setIsaccountactive(boolean isaccountactive) {
        this.isaccountactive = isaccountactive;
    }
    public boolean isSiteyononaydurum() {
        return this.siteyononaydurum;
    }
    
    public void setSiteyononaydurum(boolean siteyononaydurum) {
        this.siteyononaydurum = siteyononaydurum;
    }
    public String getActivationcode() {
        return this.activationcode;
    }
    
    public void setActivationcode(String activationcode) {
        this.activationcode = activationcode;
    }
    public String getUsercity() {
        return this.usercity;
    }
    
    public void setUsercity(String usercity) {
        this.usercity = usercity;
    }
    public boolean isIsgold() {
        return this.isgold;
    }
    
    public void setIsgold(boolean isgold) {
        this.isgold = isgold;
    }
    public int getServerpermlevel() {
        return this.serverpermlevel;
    }
    
    public void setServerpermlevel(int serverpermlevel) {
        this.serverpermlevel = serverpermlevel;
    }
    public String getAvatarpath() {
        return this.avatarpath;
    }
    
    public void setAvatarpath(String avatarpath) {
        this.avatarpath = avatarpath;
    }
    public boolean isIshidden() {
        return this.ishidden;
    }
    
    public void setIshidden(boolean ishidden) {
        this.ishidden = ishidden;
    }
    public Integer getAtayanuserid() {
        return this.atayanuserid;
    }
    
    public void setAtayanuserid(Integer atayanuserid) {
        this.atayanuserid = atayanuserid;
    }
    public Date getGoldexpirydate() {
        return this.goldexpirydate;
    }
    
    public void setGoldexpirydate(Date goldexpirydate) {
        this.goldexpirydate = goldexpirydate;
    }
    public Set getRoomlevelpermsets() {
        return this.roomlevelpermsets;
    }
    
    public void setRoomlevelpermsets(Set roomlevelpermsets) {
        this.roomlevelpermsets = roomlevelpermsets;
    }
    public Set getServerlvlipbans() {
        return this.serverlvlipbans;
    }
    
    public void setServerlvlipbans(Set serverlvlipbans) {
        this.serverlvlipbans = serverlvlipbans;
    }
    public Set getUserprivatemsglogs() {
        return this.userprivatemsglogs;
    }
    
    public void setUserprivatemsglogs(Set userprivatemsglogs) {
        this.userprivatemsglogs = userprivatemsglogs;
    }
    public Set getServerlvlnickbans() {
        return this.serverlvlnickbans;
    }
    
    public void setServerlvlnickbans(Set serverlvlnickbans) {
        this.serverlvlnickbans = serverlvlnickbans;
    }
    public Set getScores() {
        return this.scores;
    }
    
    public void setScores(Set scores) {
        this.scores = scores;
    }
    public Set getUsercnnlogs() {
        return this.usercnnlogs;
    }
    
    public void setUsercnnlogs(Set usercnnlogs) {
        this.usercnnlogs = usercnnlogs;
    }
    public Set getRoomlevelbanlogs() {
        return this.roomlevelbanlogs;
    }
    
    public void setRoomlevelbanlogs(Set roomlevelbanlogs) {
        this.roomlevelbanlogs = roomlevelbanlogs;
    }
    public Set getUserbuddydatas() {
        return this.userbuddydatas;
    }
    
    public void setUserbuddydatas(Set userbuddydatas) {
        this.userbuddydatas = userbuddydatas;
    }
    public Set getGorevhavuzus() {
        return this.gorevhavuzus;
    }
    
    public void setGorevhavuzus(Set gorevhavuzus) {
        this.gorevhavuzus = gorevhavuzus;
    }




}


